//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hubbell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MejoraContinuaProyectos
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Categoria { get; set; }
        public string Integrantes { get; set; }
        public string RecoleccionDatos { get; set; }
        public string SituacionActualFoto { get; set; }
        public string CausaPotencial { get; set; }
        public string CausaRaiz { get; set; }
        public string MedidasMejora { get; set; }
        public string FechaInicio { get; set; }
        public string ResultadoFoto { get; set; }
        public string Beneficios { get; set; }
        public string Comentarios { get; set; }
        public string FechaCierre { get; set; }
    }
}
