CREATE DATABASE Hubbell;
USE Hubbell;
CREATE TABLE EmpleadosMes(
	Id INT PRIMARY KEY IDENTITY(1,1),
	NumReloj INT,
	Fecha VARCHAR(10)
);

CREATE TABLE FotoEmpleadosMes(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Img VARCHAR(MAX),
	Fecha VARCHAR(10)
);

CREATE TABLE Vacantes(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Img VARCHAR(MAX),
	Fecha VARCHAR(10),
	Planta VARCHAR(7),
);

CREATE TABLE Topicos(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Img VARCHAR(MAX),
	Fecha VARCHAR(10)
);