CREATE DATABASE Hubbell;
USE Hubbell;
CREATE TABLE EmpleadosMes(
	Id INT PRIMARY KEY IDENTITY(1,1),
	NumReloj INT,
	Fecha DATETIME DEFAULT GETDATE()
);

CREATE TABLE FotoEmpleadosMes(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Img VARCHAR(MAX),
	Fecha DATETIME DEFAULT GETDATE()
);